export const GET_CUSTOMERS = "GET_CUSTOMERS"
export const ADD_CUSTOMER = "ADD_CUSTOMER"
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER"
export const GET_TASKS = "GET_TASKS"
export const GET_CATEGORYLIST = "GET_CATEGORYLIST"
export const ADD_TASK = "ADD_TASK"
export const GET_PROFILE = "GET_PROFILE"
export const UPDATE_PROFILE = "UPDATE_PROFILE"
export const ADD_INVESTMENTS = "ADD_INVESTMENTS"
export const ADD_FUND =  "ADD_FUND"
export const UPDATE_INVEST_CONST_DATA = "UPDATE_INVEST_CONST_DATA" 
export const GET_INVEST_CONST_DATA = "GET_INVEST_CONST_DATA"


